web:
  build: .
  links:
   - db
  ports:
   - "3000:3000"
   - "35729:35729"
  environment: 
   NODE_ENV: development
  volumes:
    - .:/home/app/harpi
    - /home/app/harpi/node_modules
db:
  image: mongo
  ports: 
   - "27017:27017"
  volumes:
<<<<<<< HEAD
   - ./mongo_data:/data/db
=======
    - ./data/db:/data/db
>>>>>>> 1c714d55a9f25696f7da35bc540cc75618935def

