version: '2'

services:
  web:
    build:
      context: .
      dockerfile: ./.docker/dev/Dockerfile
    ports:
      - "3000:3000"
      - "35729:35729"
      - "5858:5858"
    environment: 
      NODE_ENV: development
    volumes:
      - .:/home/app/harpi
      - /home/app/harpi/node_modules
      - /home/app/harpi/public/lib
  db:
    ports: 
      - "27017:27017"
    volumes:
      - ./data/db:/data/db

