version: '2'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment: 
      NODE_ENV: production
    command: ["grunt", "prod", "--force"]
  db:
    image: mongo:3.3